title: Patient Research
description: Evidenzorientierte, fortlaufend aktualisierte Dossiers zu komplexen medizinischen Fragen.
url: https://open-research-works.github.io
baseurl: /Patient-Research
lang: de-DE
prelaunch: true
markdown: kramdown
permalink: pretty
